### PR TITLE
Add Member field+filter for Titles

### LINKED ISSUE #208: Add member field to title model
We need this for the new album titles.

### PR DESCRIPTION
**Pull request by LatidoReMe**
Close #208

### CODE REVIEW

**Comment by summertriangle-dev** [comment]
That said, can you change the value formatting too before merging this? (Or I can do it if you're busy, but I didn't want to edit your branch without asking first)

**Comment by LatidoReMe** [comment]
Ok so I'm sorry for not replying back sooner (I haven't checked Github in a few days) but I can probably? do it if you tell me how you want the value formatting done. I just didn't know how we should rework it, so I avoided implementing it for now.

I've been busier lately though so I'm fine if you do it instead! Whatever works out best.

**Comment by summertriangle-dev** [comment]
It was pretty much just adding a # sign in front, I've gone ahead and done that.

**Comment by LatidoReMe** [comment]
Ah, ok then! I'll merge this now then, and db can push it whenever she's available.

**Pull request merged**
